name: Docker Build, Test and Push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: docker.io/cosibe23/my-website

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image 
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ env.IMAGE_NAME }}:latest
          load: true 

      - name: Run container and test it
        run: |
          docker run -d --name test-container -p 8080:80 $IMAGE_NAME:latest
          sleep 5 # give it time to start
          curl -s http://localhost:8080 | grep "Hello from Docker"

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          
